RoleBasedAuthentication/Controllers/ClassController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RoleBasedAuthentication.Models;
using RoleBasedAuthentication.RepoHelpers;
namespace RoleBasedAuthentication.Controllers
{
    [Authorize]
    public class ClassController : Controller
    {
        private readonly ClassHelper _classhelper;
        public ClassController(
            ClassHelper classhelper
        )
        {
            _classhelper = classhelper;
        }
        #region Class

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult ClassModalPartial()
        {
            return PartialView();
        }

        [HttpPost]
        public IActionResult AddClass(ClassModal mdl)
        {
            _classhelper.addClass(mdl);
            return Json("Done");
        }

        [HttpGet]
        public IActionResult ListClass()
        {
            return PartialView(_classhelper.GetList());
        }

        [HttpPost]
        public IActionResult DeleteClass(int id)
        {
            _classhelper.DeleteClass(id);
            return Json("Deletion completed");
        }

        [HttpGet]
        public IActionResult UpdatePartial(int id)
        {
            return PartialView(_classhelper.GetDetails(id));
        }

        [HttpPost]
        public IActionResult Update(ClassModal mdl)
        {
            _classhelper.UpdatedClass(mdl);
            return Json("Updated Successfully");
        }

        [HttpGet]
        public IActionResult ClassDropdownpartial()
        {
            return PartialView(_classhelper.GetClassesDropDown(""));
        }
        #endregion
    }
}

RoleBasedAuthentication/Controllers/StudentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RoleBasedAuthentication.RepoHelpers;

namespace RoleBasedAuthentication.Controllers
{
    [Authorize]
    public class StudentController : Controller
    {
        private readonly UsersHelper _users;
        public StudentController(
            UsersHelper users
        )
        {
            _users = users;
        }

        #region Student

        public IActionResult Dashboard()
        {
            return View();
        }
        public async Task<IActionResult> List()
        {
            var result = await _users.GetStudents();
            return PartialView("_List", result);
        }
        #endregion
    }
}

RoleBasedAuthentication/Views/Shared/Table.cshtml
@model List<MyModal>
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<table class="table">
    <tr>
        <th>
            Name
        </th>
        <th>Roll no</th>
        <th>Adress</th>
        <th>State</th>
        <th>Action</th>
    </tr>
    @foreach(var data in Model)
    {
        <tr>
            <td>@data.name</td>
            <td>@data.roll</td>
            <td>@data.adress</td>
            <td>@data.state</td>
            <td>
                <button class="alert-danger dletebtn" onclick="deleteRecord(@data.roll)">Delete</button>
                <button onclick="updateRecord(@data.roll)">Update</button>
            </td>
        </tr>
    }
</table>

RoleBasedAuthentication/Views/Shared/_FormView.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<form>
    <div class="form-floating mb-3">
        <label for="name">Your Name : </label>
        <input type="text" name="name" value="" id="name" />
    </div>
    <br />

    <div class="form-floating mb-3">
        <label for="roll">Roll No : </label>
        <input type="number" name="roll" id="roll" />
    </div>
    <br />
    <div class="form-floating mb-3">
        <label for="adress">Adress : </label>
        <input type="text" name="adress" id="adress"/>
    </div>
    <br />
    <div class="form-floating mb-3">
        <label for="state">State : </label>
        <input type="text" name="state" id="state" />
    </div>
    <div class="row">
        <div class="col-md-12">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button"  class="btn btn-primary submit-data" id="submitForm">Save changes</button>
    </div>
    </div>
    
</form>



    <script>
        $(document).ready(function(){
            $(".submit-data").click(function(e){
            e.preventDefault();

            $.ajax({
                type : "POST",
                url : "/Home/AddUser",
                data : {
                    name : $("#name").val(),
                    roll : $("#roll").val(),
                    adress : $("#adress").val(),
                    state : $("#state").val()
                },
                dataType: "json",
                contentType: "application/x-www-form-urlencoded; charset=UTF-8",
                    success: function(response) {
                    console.log("Karan");
                    UpdateTableData();

            },
                error: function(jqXHR, textStatus, errorThrown) {
                    console.error("Error submitting data:", textStatus, errorThrown);
                }
            })
        })

        });
    </script>

RoleBasedAuthentication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RoleBasedAuthentication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RoleBasedAuthentication.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/notyf@3/notyf.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RoleBasedAuthentication</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                            @if (User.IsInRole("Director"))     //Director can see both students and tecahers list

                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Teacher" asp-action="Dashboard">Teachers</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Dashboard">Students</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Class" asp-action="Index">Classes</a>
                                </li>
                            }
                            @if (User.IsInRole("Teacher"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Teacher" asp-action="Dashboard">Teachers</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Dashboard">Students</a>
                                </li>
                            }
                        </ul>
                    }
                    
                    <partial name="_LoginPartial" />
                    </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - RoleBasedAuthentication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootbox@6.0.4/dist/bootbox.all.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <!-- jQuery -->
    @* <script src="https://code.jquery.com/jquery-3.7.0.min.js"></script> *@

    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css" />

    <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>


    <link rel="stylesheet" href="~/css/jquery.bs_pagination.bs2.css" asp-append-version="true" />
    <script src="~/js/jquery.bs_pagination.js"></script>
    <script src="~/js/en.min.js"></script>


    @await RenderSectionAsync("Scripts", required: false)
    <script src="https://cdn.jsdelivr.net/npm/notyf@3/notyf.min.js"></script>
    @await Component.InvokeAsync("Notyf")
</body>
</html>